// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wjibhdckcehguncrcfrl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndqaWJoZGNrY2VoZ3VuY3JjZnJsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc5MDY4ODksImV4cCI6MjA2MzQ4Mjg4OX0.lzHtAssXN3ZwAtuz3Qm_RVUy8T3f7F9yINSUkfDim7U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);